title: Shubham Pandey Portfolio
logo: /assets/img/logo.png
description: Welcome to my portfolio site please explore to my and skills and experince.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
