title: <p align="center"> Shubham Portfolio </p>
logo: /assets/img/logo2.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shubham-pandey-0876691a0/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Actively participates kaggle competitions and also write article on ML model on Medium
  <br>
  </p>
